### PR TITLE
Upgrade default client url's to https

### PR DESCRIPTION
**Pull request by skumar951**
These packages are all available over https:
- [http://mygene.info/v3](https://smart-api.info/ui/59dce17363dce279d389100834e43648)
- [http://myvariant.info/v1](https://smart-api.info/ui/09c8782d9f4027712e65b95424adba79)
- [http://mychem.info/v1](https://smart-api.info/ui/8f08d1446e0bb9c2b323713ce83e2bd3)
- [http://mydisease.info/v1](https://smart-api.info/ui/671b45c0301c8624abbd26ae78449ca2)
- [t.biothings.io/v1](https://smart-api.info/ui/f7943e6167166b3ea9e4b8be08f45fa6)

"mygeneset.info/v1" returns a 404 url regardless of http or https.

### CODE REVIEW

**Comment by skumar951** [comment]
@newgene Any chance we could get this merged in? The http url's get blocked by my company's IT policy, so https would be much appreciated.

**Comment by newgene** [comment]
Thanks @skumar951! Just merged.

**Comment by newgene** [comment]
@skumar951 I tested locally for the `https://mygeneset.info/v1`, it seems working fine for me. Does it still return 404 for you?

**Comment by skumar951** [comment]
Yup, it works! Thank you @newgene!

**Comment by newgene** [comment]
FYI, just released a new `v0.3.1` version with this change. Thanks @skumar951

**Pull request merged**
